sudo: false
language: php
php:
  - 7.0
  - 7.1
env:
  - SYMFONY="2.7.*"
  - SYMFONY="~3.0"
services:
  - elasticsearch
install:
  - composer require --no-update symfony/symfony:${SYMFONY}
before_script:
  - composer install --no-interaction --prefer-dist
script:
  - vendor/bin/phpunit --coverage-clover=coveralls.clover
  - vendor/bin/phpcs -p --standard=PSR2 --ignore=vendor/,Tests/app/,Resources/public/ ./
after_script:
  - vendor/bin/coveralls